section [[
Ninja file for bang
This file is is generated by running bootstrap.sh
]]

section [[
This file is part of bang.

bang is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

bang is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with bang.  If not, see <https://www.gnu.org/licenses/>.

For further information about bang you can visit
https://cdelord.fr/bang
]]

local F = require "F"
local fs = require "fs"

section "Build directories"

var "builddir" ".build"

F"bin test doc" : words() : foreach(function(dir)
    var (dir) (fs.join("$builddir", dir))
end)

section "Compilation"

rule "luax" {
    description = "LUAX $out",
    command = "luax -q -o $out $in",
}

local has_ext = F.curry(function(ext, name)
    return fs.ext(name) == ext
end)

local sources = fs.walk "src"
    : filter(has_ext ".lua")
    : sort()

build "$bin/bang" {"luax", sources}
default "$bin/bang"

section "Tests"

rule "run_test" {
    description = "BANG $in",
    command = "$bin/bang -q $in -o $out",
}

rule "diff" {
    description = "DIFF $in",
    command = "diff $in && touch $out",
}

build "$test/test.ninja" {"run_test", "test/test.lua"} {
    implicit_in = "$bin/bang",
}
build "$test/test.ok" {"diff", {"$test/test.ninja", "test/test.ninja"}}

build "test" {"phony", "$test/test.ok"}
default "test"
