section [[
Ninja file for bang
This file is generated by running bootstrap.sh
]]

section [[
This file is part of bang.

bang is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

bang is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with bang.  If not, see <https://www.gnu.org/licenses/>.

For further information about bang you can visit
https://cdelord.fr/bang
]]

local F = require "F"
local fs = require "fs"

help.name "Bang"
help.description [[Ninja file for building $name]]
help.epilog [[Without any arguments, Ninja will compile and test $name.]]

---------------------------------------------------------------------
-- Build directories
---------------------------------------------------------------------

section "Build directories"

var "builddir" ".build"

F"bin test doc" : words() : foreach(function(dir)
    var (dir) (fs.join("$builddir", dir))
end)

clean "$builddir"

---------------------------------------------------------------------
-- Compilation
---------------------------------------------------------------------

section "Compilation"

build "$bin/bang" {
    description = "LUAX $out",
    command = "luax -q -o $out $in",

    ls "src/*.lua",
    ls "lib/*.lua",
    build "$builddir/version" {
        description = "GIT version",
        command = "echo -n `git describe --tags` > $out",
        implicit_in = ".git/refs/tags .git/index",
    }
}

phony "compile" { "$bin/bang" }
default "compile"
help "compile" "compile $name"

install "bin" "$bin/bang"

---------------------------------------------------------------------
-- Tests
---------------------------------------------------------------------

section "Tests"

build "$test/test.ninja" { "test/test.lua",
    description = "BANG $in",
    command = {
        "rm -f",
            "$test/tmp/new_file.txt",
            "$test/test.hlp",
        ";",
        "$bin/bang -q $in -o $out -- arg1 arg2 -x=y",
    },
    implicit_in = "$bin/bang",
    implicit_out = { "$test/tmp/new_file.txt", "$test/test.hlp" },
}

rule "diff" {
    description = "DIFF $in",
    command = "diff $in && touch $out",
}

phony "test" {
    build "$test/test.ok"     {"diff", {"$test/test.ninja",       "test/test.ninja"}},
    build "$test/new_file.ok" {"diff", {"$test/tmp/new_file.txt", "test/new_file.txt"}},
    build "$test/test.hlp.ok" {"diff", {"$test/test.hlp",         "test/test.hlp"}},
}

default "test"
help "test" "test $name"
